### ISSUE TITLE
Use GitHub repository as server?

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/librepcb-api#4]
Just a stupid question:
Why not simply create a repository on GitHub, create a json file in it, and redirect https://api.librepcb.org/v1/libraries to that file? As we do not yet need to transfer data from the application to the server, this should be enough for the beginning.

Advantages:
- KISS - much less complexity!
- Transparency - Everyone can see how it works and who has changed which library and when.
- Everyone can ask for adding or updating a library just by creating a pull request (cool, isn't it?).
- We also need a way to provide library icons (*.png) - GitHub can do this too, just check in the icons.

Opinions?

**Comment by dbrgn** [comment]
When do you plan to add a feature to upload new libraries from the software? More than a year from now?

We can do this of course. But keep in mind that Github has rate limiting, so if a lot of people _would_ download libraries, it's possible that the downloads become slow or don't work.

Regarding the API updates, I already prepared most of the update on my laptop. We just need to discuss a few things about it next Monday before I do the change.

If you decide to use Github for now, we can also delay that.

**Comment by ubruhin** [comment]
> When do you plan to add a feature to upload new libraries from the software? More than a year from now?

Yes, definitively more than a year from now.

> We can do this of course. But keep in mind that Github has rate limiting, so if a lot of people would download libraries, it's possible that the downloads become slow or don't work.

Doesn''t that rate limit only apply to the Github API (which we would not use)? But even if this becomes a problem, we could set up a mirror of the json file on our own server (just a file server which fetches the files from Github from time to time). This would still be much less complex than a whole API server.

> Regarding the API updates, I already prepared most of the update on my laptop. We just need to discuss a few things about it next Monday before I do the change.

Discussing such things would also become easier if the json file is hosted on Github, because we could create pull requests with reviews and comments :)

> If you decide to use Github for now, we can also delay that.

Yes, I think you should delay it for the moment. Maybe we get more opinions from @rnestler or @0xB767B. But in the meantime I will create a new repository for the json file and make some tests to see how it works.

If we go that way, I'm sorry for the time you spent already for the API server :wink: I have underestimated the effort, complexity and disadvantages of an own API server...

**Comment by ubruhin** [comment]
New repository: https://github.com/LibrePCB/librepcb-api-static

And the API is already running: https://raw.githubusercontent.com/LibrePCB/librepcb-api-static/master/v1/libraries :stuck_out_tongue_winking_eye:

**Comment by dbrgn** [comment]
> I have underestimated the effort, complexity and disadvantages of an own API server...

The effort and complexity so far are actually quite small. I just didn't find the time to work on it :)

But +1 on the static JSON approach for now.

**Comment by ubruhin** [comment]
This is actually solved a long time ago, so I'm closing it...
