### ISSUE TITLE
Take application version into account when delivering a list of libraries

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/librepcb-api#5]
Currently the API response of `/api/v1/libraries` contains all available libraries, no matter what file version they have. So if you use an older application version (e.g. with file format v0.1), you also get libraries with a newer file format (e.g. v0.2). But the application can't open these libraries because of the changed file format.

So the client (i.e. the application) needs to specify its version when asking the server for libraries. I think we can do this by using HTTP headers, for example:

```
X-LibrePCB-AppVersion: 0.1
X-LibrePCB-AppGitHash: 0385957012d0a103fc56d08dd55fe0b7c466710f
```

With this information, the server can filter out incompatible libraries in its response.

@dbrgn Would you agree with that? Is this functionality supported by the Django REST Framework?

**Comment by ubruhin** [comment]
Btw, another solution would be to implement this logic on client side (filtering out any libraries with incompatible file format). But I think it's better to do this on server side to reduce bandwidth usage (avoid useless information in the API response).

**Comment by dbrgn** [comment]
I agree about implementing this on the server side.

Filtering with HTTP headers sounds like a good idea.

If you create a simple specification of headers and how they work, I could try to implement it with DRF. Shouldn't be too hard.

**Comment by ubruhin** [comment]
Another method would be to use a query for that, e.g.

    GET https://api.librepcb.org/api/v1/libraries?format_version=0.1

Maybe this is simpler to implement than the variant with HTTP headers...

Anyway, IMHO it should be possible to use a simple web server to host the librepcb API (i.e. a standard web server which just serves some json files). So we should keep the version filtering as simple as possible.

But for a *completely* static API the version number probably needs to be embedded into the URL, for example

    GET https://api.librepcb.org/api/v1/libraries/v0.1

maybe that variant wouldn't be too bad? This way it should (theoretically) even be possible to use a local directory or network share (with some json files in it) as API endpoint, without the need for any webserver (could be useful at least for testing). This concept would follow KISS, which I like ;)

**Comment by dbrgn** [comment]
How would you handle uploading / contributing libraries with the static API? That was one of the goals for the API, even if there's no interface for that yet, right?

> without the need for any webserver

You always need a webserver to serve content over HTTP :wink:

**Comment by ubruhin** [comment]
> How would you handle uploading / contributing libraries with the static API?

For the official API (api.librepcb.org) we should of course use a dynamic API to support all features we want to have (like contributing). But there are situations where someone wants to use his own server, for example companies often want to use only their own libraries instead of publicly available libraries. In such situation a contributing feature might not be necessary, just fetching of libraries is needed. In that case a static API would be enough.

> You always need a webserver to serve content over HTTP

I think the API does not specify the protocol to use. just replace http:// by file:// and the json files are fetched directly from the local drive or a network share. I guess Qt supports that out of the box, it doesn't matter which protocol is used to fetch a file.

EDIT: Quickly tested it, just set the API URL in the librepcb workspace settings to e.g. `file:///home/me/librepcb-api-static` instead of `https://api.librepcb.org` and the library manager fetches the library list from that directory :smiley: That's really cool! This wouldn't be possible if we used headers or queries for specifying the application version...

**Comment by dbrgn** [comment]
Ah, I see. That's a good argument, we should probably just specify an API endpoint in terms of an URI to a root with subresources.

**Comment by ubruhin** [comment]
I started to document the API: https://docs.librepcb.org/_branches/add_api_documentation/#api

**Comment by ubruhin** [comment]
Done - the new API is now in use.
